### ISSUE TITLE
qt5-kde-devel build fails on High Sierra with auto_ptr errors

### ISSUE THREAD

**Issue by mfuhrer** [RJVB/macstrop#15]
Hi René,

I'm just trying to build qt5-kde-devel with the goal of eventually building KDevelop (there are a couple KDevelop issues on my Linux desktop at work that I'd like to try to debug and fix from a MacPorts build at home). Unfortunately qt5-kde-devel fails when building the 3rd party mapbox-gl-native package, which in turn includes some packaged boost libs : 

`:info:build /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6/qtlocation/src/3rdparty/mapbox-gl-native/deps/boost/1.62.0/include/boost/smart_ptr/scoped_ptr.hpp:74:31: error: no template named 'auto_ptr' in namespace 'std'`
`:info:build     explicit scoped_ptr( std::auto_ptr<T> p ) BOOST_NOEXCEPT : px( p.release() )`

clang complains about a missing std::auto_ptr, identical to [the issue discussed here](https://github.com/TRIQS/triqs/issues/523). I've found that by adding

`-D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR`

to the Makefile in

`/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtlocation/src/3rdparty/mapbox-gl-native`

the package proceeds to build successfully. I'll now need to refresh myself on updating portfiles, and will give this a try to get a successful qt5-kde-devel build and installation. 

Just curious if you encountered this issue, or perhaps you are building on a different macOS release?

**Comment by RJVB** [comment]
Hi,

No, I haven't seen this, but then I'm still running OS X 10.9 . I'll see if I can figure out a fix (or wait until port:qt59-qtlocation is updated).

May I assume this is a regression in 5.9.6? Annoyingly I forgot to upgrade my port;qt5-kde to 5.9.5 before bumping the devel port to the current release but I'll fix that as soon as I get to it.

Meanwhile, be aware that port:kf5-kdevelop is quite heavily patched so it's not really representative for stock. That said, if the issue you're seeing doesn't occur in my version there's a chance that I might have an idea about it ;)

**Comment by RJVB** [comment]
>`-D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR`

Could it also be a solution to build with something a bit less new-fangled than C++17?

**Comment by RJVB** [comment]
The question would of course be how to achieve this. Qt's build system isn't always very well documented.

If this error bites only in a single or handful of files the easy fix would be to define the CPP token at the top of those files. That can be done via a patchfile, much more straightforward than injecting a -D option into the compiler arguments.
Note that such a mod could also be applied to the embedded boost copy, that would probably require even less changes.

**Comment by mfuhrer** [comment]
Thanks for the Portfile update and patch. I'm keen to try it out but am running into a seemingly unrelated patch issue (which I did not encounter last night):

```
% sudo port selfupdate
...
% sudo port clean qt5-kde-devel
...
% sudo port install -v qt5-kde-devel
...
--->  Applying patch-add-cups-printsupport.diff
Executing:  cd "/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6" && /usr/bin/patch -Np1 < '/opt/local/site-ports/aqua/qt5-kde-devel/files/qt596//patch-add-cups-printsupport.diff'
patching file qtbase/src/plugins/printsupport/printsupport.pro
patching file qtbase/src/printsupport/dialogs/dialogs.pri
patching file qtbase/src/printsupport/dialogs/qcupspagesetupdialog.cpp
patching file qtbase/src/printsupport/dialogs/qcupspagesetupdialog.h
patching file qtbase/src/printsupport/dialogs/qcupsprintdialog.h
patching file qtbase/src/printsupport/dialogs/qpagesetupdialog.cpp
patching file qtbase/src/printsupport/dialogs/qpagesetupdialog.h
patching file qtbase/src/printsupport/dialogs/qpagesetupdialog_mac.mm
patching file qtbase/src/printsupport/dialogs/qpagesetupdialog_unix.cpp
patching file qtbase/src/printsupport/dialogs/qprintdialog.h
patching file qtbase/src/printsupport/dialogs/qprintdialog.qrc
patching file qtbase/src/printsupport/dialogs/qprintdialog_mac.mm
patching file qtbase/src/printsupport/dialogs/qprintdialog_unix.cpp
patching file qtbase/src/printsupport/dialogs/qprintpreviewdialog.cpp
patching file qtbase/src/printsupport/dialogs/qprintpreviewdialog.h
patching file qtbase/src/printsupport/kernel/kernel.pri
patching file qtbase/src/printsupport/kernel/qplatformprintplugin.cpp
patching file qtbase/src/printsupport/widgets/widgets.pri
...
--->  Applying patch-printpreview-pdf-export.diff
Executing:  cd "/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6" && /usr/bin/patch -Np1 < '/opt/local/site-ports/aqua/qt5-kde-devel/files/qt593/patch-printpreview-pdf-export.diff'
patching file qtbase/src/printsupport/dialogs/qprintdialog.qrc
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file qtbase/src/printsupport/dialogs/qprintdialog.qrc.rej
patching file qtbase/src/printsupport/dialogs/qprintpreviewdialog.cpp
Reversed (or previously applied) patch detected!  Skipping patch.
6 out of 6 hunks ignored -- saving rejects to file qtbase/src/printsupport/dialogs/qprintpreviewdialog.cpp.rej
patching file qtbase/src/printsupport/dialogs/qprintpreviewdialog.h
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file qtbase/src/printsupport/dialogs/qprintpreviewdialog.h.rej
Command failed:  cd "/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6" && /usr/bin/patch -Np1 < '/opt/local/site-ports/aqua/qt5-kde-devel/files/qt593/patch-printpreview-pdf-export.diff'
Exit code: 1`
```

Looks like the two diff files are applying identical patches to qprintdialog.qrc, qprintpreviewdialog.cpp, and qprintpreviewdialog.h. Can you take a look?

**Comment by RJVB** [comment]
Oh dang, I completely forgot that I already had another patch in that same directory. Fortunately the 2 patches have no overlap.

Fixed now, apologies.

R

**Comment by mfuhrer** [comment]
Thanks René, the build now completes successfully. I'm still encountering a problem during staging to destroot; looks like ranlib on libQt5Bootstrap.a fails because this lib was previously deleted. Continuing to investigate if this is a bug on the Qt build side...

```
% sudo port clean qt5-kde-devel
...
% sudo port -v install qt5-kde-devel
...
--->  Staging qt5-kde-devel into destroot
. changed
	gid expected 0 found 80 modified
./usr missing (created)
. missing (directory not created: File exists)
./Applications missing (created)
./Developer missing (created)
./Library missing (created)
. changed
	gid expected 80 found 0 modified
./bin missing (created)
./etc missing (created)
./include missing (created)
./lib missing (created)
./lib/pkgconfig missing (created)
./libexec missing (created)
./sbin missing (created)
./share missing (created)
./share/doc missing (created)
./share/info missing (created)
./share/man missing (created)
./share/man/cat1 missing (created)
./share/man/cat2 missing (created)
./share/man/cat3 missing (created)
./share/man/cat4 missing (created)
./share/man/cat5 missing (created)
./share/man/cat6 missing (created)
./share/man/cat7 missing (created)
./share/man/cat8 missing (created)
./share/man/cat9 missing (created)
./share/man/catl missing (created)
./share/man/catn missing (created)
./share/man/man1 missing (created)
./share/man/man2 missing (created)
./share/man/man3 missing (created)
./share/man/man4 missing (created)
./share/man/man5 missing (created)
./share/man/man6 missing (created)
./share/man/man7 missing (created)
./share/man/man8 missing (created)
./share/man/man9 missing (created)
./share/man/manl missing (created)
./share/man/mann missing (created)
./share/nls missing (created)
./share/nls/C missing (created)
./share/nls/af_ZA.ISO8859-1 missing (created)
./share/nls/af_ZA.ISO8859-15 missing (created)
./share/nls/bg_BG.CP1251 missing (created)
./share/nls/cs_CZ.ISO8859-2 missing (created)
./share/nls/da_DK.ISO8859-1 missing (created)
./share/nls/da_DK.ISO8859-15 missing (created)
./share/nls/de_AT.ISO8859-1 missing (created)
./share/nls/de_AT.ISO8859-15 missing (created)
./share/nls/de_CH.ISO8859-1 missing (created)
./share/nls/de_CH.ISO8859-15 missing (created)
./share/nls/de_DE.ISO8859-1 missing (created)
./share/nls/de_DE.ISO8859-15 missing (created)
./share/nls/el_GR.ISO8859-7 missing (created)
./share/nls/en_AU.ISO8859-1 missing (created)
./share/nls/en_AU.ISO8859-15 missing (created)
./share/nls/en_AU.US-ASCII missing (created)
./share/nls/en_CA.ISO8859-1 missing (created)
./share/nls/en_CA.ISO8859-15 missing (created)
./share/nls/en_CA.US-ASCII missing (created)
./share/nls/en_GB.ISO8859-1 missing (created)
./share/nls/en_GB.ISO8859-15 missing (created)
./share/nls/en_GB.US-ASCII missing (created)
./share/nls/en_NZ.ISO8859-1 missing (created)
./share/nls/en_NZ.ISO8859-15 missing (created)
./share/nls/en_NZ.US-ASCII missing (created)
./share/nls/en_US.ISO8859-1 missing (created)
./share/nls/en_US.ISO8859-15 missing (created)
./share/nls/es_ES.ISO8859-1 missing (created)
./share/nls/es_ES.ISO8859-15 missing (created)
./share/nls/et_EE.ISO8859-15 missing (created)
./share/nls/fi_FI.ISO8859-1 missing (created)
./share/nls/fi_FI.ISO8859-15 missing (created)
./share/nls/fr_BE.ISO8859-1 missing (created)
./share/nls/fr_BE.ISO8859-15 missing (created)
./share/nls/fr_CA.ISO8859-1 missing (created)
./share/nls/fr_CA.ISO8859-15 missing (created)
./share/nls/fr_CH.ISO8859-1 missing (created)
./share/nls/fr_CH.ISO8859-15 missing (created)
./share/nls/fr_FR.ISO8859-1 missing (created)
./share/nls/fr_FR.ISO8859-15 missing (created)
./share/nls/hi_IN.ISCII-DEV missing (created)
./share/nls/hr_HR.ISO8859-2 missing (created)
./share/nls/hu_HU.ISO8859-2 missing (created)
./share/nls/is_IS.ISO8859-1 missing (created)
./share/nls/is_IS.ISO8859-15 missing (created)
./share/nls/it_CH.ISO8859-1 missing (created)
./share/nls/it_CH.ISO8859-15 missing (created)
./share/nls/it_IT.ISO8859-1 missing (created)
./share/nls/it_IT.ISO8859-15 missing (created)
./share/nls/ja_JP.SJIS missing (created)
./share/nls/ja_JP.eucJP missing (created)
./share/nls/ko_KR.eucKR missing (created)
./share/nls/la_LN.ISO8859-1 missing (created)
./share/nls/la_LN.ISO8859-15 missing (created)
./share/nls/la_LN.ISO8859-2 missing (created)
./share/nls/la_LN.ISO8859-4 missing (created)
./share/nls/la_LN.US-ASCII missing (created)
./share/nls/lt_LT.ISO8859-4 missing (created)
./share/nls/nl_BE.ISO8859-1 missing (created)
./share/nls/nl_BE.ISO8859-15 missing (created)
./share/nls/nl_NL.ISO8859-1 missing (created)
./share/nls/nl_NL.ISO8859-15 missing (created)
./share/nls/no_NO.ISO8859-1 missing (created)
./share/nls/no_NO.ISO8859-15 missing (created)
./share/nls/pl_PL.ISO8859-2 missing (created)
./share/nls/pt_BR.ISO8859-1 missing (created)
./share/nls/pt_PT.ISO8859-1 missing (created)
./share/nls/pt_PT.ISO8859-15 missing (created)
./share/nls/ro_RO.ISO8859-2 missing (created)
./share/nls/ru_RU.CP866 missing (created)
./share/nls/ru_RU.ISO8859-5 missing (created)
./share/nls/ru_RU.KOI8-R missing (created)
./share/nls/sk_SK.ISO8859-2 missing (created)
./share/nls/sl_SI.ISO8859-2 missing (created)
./share/nls/sv_SE.ISO8859-1 missing (created)
./share/nls/sv_SE.ISO8859-15 missing (created)
./share/nls/tr_TR.ISO8859-9 missing (created)
./share/nls/uk_UA.ISO8859-5 missing (created)
./share/nls/uk_UA.KOI8-U missing (created)
./share/nls/zh_CN.eucCN missing (created)
./share/nls/zh_TW.Big5 missing (created)
./share/skel missing (created)
./var missing (created)
./var/cache missing (created)
./var/db missing (created)
./var/log missing (created)
./var/run missing (created)
./var/spool missing (created)
./www missing (created)
Executing:  cd "/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build" && gmake -w install DESTDIR=/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/destroot 
gmake: Entering directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build'
cd qtbase/ && ( test -e Makefile || /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/bin/qmake -o Makefile /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6/qtbase/qtbase.pro ) && gmake -f Makefile install
gmake[1]: Entering directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase'
cd src/ && ( test -e Makefile || /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/bin/qmake -o Makefile /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6/qtbase/src/src.pro ) && gmake -f Makefile install
gmake[2]: Entering directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/src'
cd tools/bootstrap/ && ( test -e Makefile || /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/bin/qmake -o Makefile /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/qt-everywhere-opensource-src-5.9.6/qtbase/src/tools/bootstrap/bootstrap.pro ) && gmake -f Makefile install
gmake[3]: Entering directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/src/tools/bootstrap'
rm -f ../../../lib/libQt5Bootstrap.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/destrootlibQt5Bootstrap.a .obj/qlatincodec.o .obj/qtextcodec.o .obj/qutfcodec.o .obj/qglobal.o .obj/qlogging.o .obj/qmalloc.o .obj/qnumeric.o .obj/qoperatingsystemversion.o .obj/qabstractfileengine.o .obj/qbuffer.o .obj/qdatastream.o .obj/qdebug.o .obj/qdir.o .obj/qdiriterator.o .obj/qfile.o .obj/qfileinfo.o .obj/qfilesystementry.o .obj/qfilesystemengine.o .obj/qfsfileengine.o .obj/qfsfileengine_iterator.o .obj/qiodevice.o .obj/qfiledevice.o .obj/qresource.o .obj/qtemporaryfile.o .obj/qtextstream.o .obj/qsavefile.o .obj/qstandardpaths.o .obj/qloggingcategory.o .obj/qloggingregistry.o .obj/qcoreapplication.o .obj/qcoreglobaldata.o .obj/qmetatype.o .obj/qvariant.o .obj/qsystemerror.o .obj/quuid.o .obj/qbitarray.o .obj/qbytearray.o .obj/qarraydata.o .obj/qbytearraymatcher.o .obj/qcommandlineparser.o .obj/qcommandlineoption.o .obj/qcryptographichash.o .obj/qdatetime.o .obj/qhash.o .obj/qlist.o .obj/qlinkedlist.o .obj/qlocale.o .obj/qlocale_tools.o .obj/qmap.o .obj/qregexp.o .obj/qringbuffer.o .obj/qpoint.o .obj/qrect.o .obj/qsize.o .obj/qline.o .obj/qstring.o .obj/qstringbuilder.o .obj/qstring_compat.o .obj/qstringlist.o .obj/qversionnumber.o .obj/qvsnprintf.o .obj/qxmlutils.o .obj/qxmlstream.o .obj/qjson.o .obj/qjsondocument.o .obj/qjsonobject.o .obj/qjsonarray.o .obj/qjsonvalue.o .obj/qjsonparser.o .obj/qjsonwriter.o .obj/qdom.o .obj/qxml.o .obj/qfilesystemengine_unix.o .obj/qfilesystemiterator_unix.o .obj/qfsfileengine_unix.o .obj/qcoreapplication_mac.o .obj/qcore_mac.o .obj/qoperatingsystemversion_darwin.o .obj/qcore_mac_objc.o .obj/qcore_foundation.o .obj/qstandardpaths_mac.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s ../../../lib/libQt5Bootstrap.a
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: can't open file: ../../../lib/libQt5Bootstrap.a (No such file or directory)
gmake[3]: *** [Makefile:362: ../../../lib/libQt5Bootstrap.a] Error 1
gmake[3]: Leaving directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/src/tools/bootstrap'
gmake[2]: *** [Makefile:84: sub-bootstrap-install_subtargets] Error 2
gmake[2]: Leaving directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase/src'
gmake[1]: *** [Makefile:65: sub-src-install_subtargets] Error 2
gmake[1]: Leaving directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build/qtbase'
gmake: *** [Makefile:95: module-qtbase-install_subtargets] Error 2
gmake: Leaving directory '/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build'
Command failed:  cd "/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/build" && gmake -w install DESTDIR=/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/destroot 
Exit code: 2
```

**Comment by RJVB** [comment]
On Friday June 22 2018 10:03:50 Martin Fuhrer wrote:

If you didn't make a copy/paste error, the problem is here:

>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq \
>/opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work/destrootlibQt5Bootstrap.a

Seems unlikely that this would happen just to you or just on your OS version, but it certainly explains the error you get just afterwards!

Was this a clean build?

**Comment by mfuhrer** [comment]
Good eye! Yes, this was from a clean build (the second clean build attempt I might add), and I can verify that the snippet from the log is accurate. Are you suggesting the filename and location of destrootlibQt5Bootstrap.a is suspicious? Interestingly, here is the contents of my work directory (I haven't touched anything since the last staging to destroot failure):

```
[mfuhrer@Buzz.local: /opt/local/var/macports/build/_opt_local_site-ports_aqua_qt5-kde-devel/qt5-kde-devel/work] 
[162] ls
build  destroot  destrootlibQt5Bootstrap.a  mkspecs_cache  qt-everywhere-opensource-src-5.9.6
```

**Comment by RJVB** [comment]
So you confirm that you just ran `port install` or `port destroot` after a `port clean`?

> Are you suggesting the filename and location of destrootlibQt5Bootstrap.a is suspicious? 

Not just suspicious, it's wrong. it should be something like ..../destroot/opt/local/libexec/qt5/lib/libQt5Bootstrap.a ; destroot is just a directory that serves as a temporary install prefix. 

What's suspicious is that your destroot phase does building. The build phase should have created /path/to/build/qtbase/lib/libQt5Bootstrap.a and the destroot phase only needs to copy that file. I just rewound and redid my build and destroot phases, and that's indeed what I see:

```
:info:destroot gmake[3]: Entering directory '/path/to/qt5-kde-devel/work/build/qtbase/src/tools/bootstrap'
:info:destroot /path/to/qt5-kde-devel/work/build/qtbase/bin/qmake -install qinstall ../../../lib/libQt5Bootstrap.a /path/to/qt5-kde-devel/work/destroot/opt/local/libexec/qt5/Library/Frameworks/libQt5Bootstrap.a
:info:destroot /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s /path/to/qt5-kde-devel/work/destroot/opt/local/libexec/qt5/Library/Frameworks/libQt5Bootstrap.a

```

What does your `port work qt5-kde-devel`/build/qtbase/src/tools/bootstrap/Makefile contain? Mine has

```
../../../lib/$(TARGET):  $(OBJECTS) $(OBJCOMP)
     @test -d ../../../lib/ || mkdir -p ../../../lib/
     -$(DEL_FILE) ../../../lib/$(TARGET)
     $(AR) $(DESTDIR)$(TARGET) $(OBJECTS)
     $(RANLIB) ../../../lib/$(TARGET)
```

where DESTDIR is usually initialised to ../../../lib/

I'm not entirely certain why this doesn't go wrong on my end too...

Note that I've already seen similar cases where a library ended up in the port's workdir, next to the destroot directory, but that never yet led to errors.

**Comment by RJVB** [comment]
Thanks, I'll look into this when I get back to my Mac in a few days.

**Comment by mfuhrer** [comment]
Thanks René, qt5-kde-devel now builds successfully on High Sierra.
